language: python
python:
  - "3.8"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - export FLASK_CONFIG=testing
  - coverage run tests.py
after_success:
  - coverage report --omit '/home/travis/virtualenv/python3.8.7/lib/python3.8/site-packages/*'
  - coveralls