"""empty message

Revision ID: 414924c20150
Revises: 
Create Date: 2021-05-22 01:38:59.517630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '414924c20150'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id_dep', sa.Integer(), nullable=False),
    sa.Column('dep_name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id_dep')
    )
    op.create_table('employee',
    sa.Column('id_emp', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=True),
    sa.Column('last_name', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id_dep'], ),
    sa.PrimaryKeyConstraint('id_emp'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('department')
    # ### end Alembic commands ###
